name: Deploy WordPress

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up SSH for deployment
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SECRET }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com > ~/.ssh/known_hosts
          ssh-keyscan -t rsa 134.122.49.114 >> ~/.ssh/known_hosts

      - name: Deploy to server
        env:
          USER: toyin
          HOST: 134.122.49.114
          DEPLOY_PATH: /var/www/html
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $USER@$HOST << 'EOF'
            cd $DEPLOY_PATH
            
            # Initialize repository if not done
            if [ ! -d ".git" ]; then
              git init
              git remote add origin https://github.com/toyinogun/deploy-pipeline.git
            fi
            git pull origin main

            # Set permissions for WordPress files
            sudo chown -R www-data:www-data .
            sudo find . -type d -exec chmod 755 {} \;
            sudo find . -type f -exec chmod 644 {} \;

            # Restart Nginx
            sudo systemctl restart nginx
          EOF
