name: Deploy WordPress

on:
  push:
    branches:
      - main  # Trigger the workflow only when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up SSH for deployment
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          ssh-keyscan -t rsa 134.122.55.129 >> ~/.ssh/known_hosts

      - name: Deploy to server
        env:
          USER: toyin
          HOST: 134.122.55.129
          DEPLOY_PATH: /var/www/html
        run: |
          ssh -i ~/.ssh/id_rsa $USER@$HOST << EOF
            cd $DEPLOY_PATH
            git pull origin main
            # Set permissions for security
            chown -R www-data:www-data .
            find . -type d -exec chmod 755 {} \;
            find . -type f -exec chmod 644 {} \;
            # Restart the web server (replace apache2 with nginx if using Nginx)
            sudo systemctl restart apache2
          EOF

